language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

# faster builds on new travis setup not using sudo
sudo: false

services:
  - mysql

install:
  - '[[ -z "$CI_USER_TOKEN" ]] || composer config github-oauth.github.com ${CI_USER_TOKEN};'
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --prefer-dist --no-interaction
  - git clone -q --depth=1 -b master --recurse-submodules https://github.com/Slamdunk/codeception-mezzio-tests framework-tests
  - git --git-dir framework-tests/.git log -n 1
  - travis_retry composer update -d framework-tests --no-dev --prefer-dist --no-interaction
  - php ./vendor/bin/codecept build -c framework-tests

script:
  - php ./vendor/bin/codecept run functional -c framework-tests
