name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.1, 7.2, 7.3, 7.4]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: none

    - name: Checkout Mezzio Sample
      uses: actions/checkout@v2
      with:
        repository: Slamdunk/codeception-mezzio-tests
        path: framework-tests
        submodules: recursive

    - name: Install Mezzio Sample
      run: composer update --no-dev --prefer-dist --no-interaction
      working-directory: framework-tests

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction --no-suggest

    - name: Run test suite
      run: |
        php vendor/bin/codecept build -c framework-tests
        php vendor/bin/codecept run functional -c framework-tests
