name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.2]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: none

    - name: Install Mezzio Sample
      run: composer create-project mezzio/mezzio-skeleton --prefer-dist --no-interaction framework-tests

    - name: Copy The Tests/Site
      run: cp -rf src-test/{src,templates,test,tests,codeception.yml} framework-tests/

    - name: Copy The Config
      run: cp -f src-test/config/routes.php framework-tests/config/

    - name: Remove The Default
      run: composer remove mezzio/mezzio-fastroute
      working-directory: framework-tests

    - name: Install The Dependencies
      run: composer require -n mezzio/mezzio-laminasrouter mezzio/mezzio-laminasviewrenderer:^2 mezzio/mezzio-session-ext -n
      working-directory: framework-tests

    - name: Run test suite
      run: php -d register_argc_argv=On vendor/bin/codecept run functional -c framework-tests
