name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.0]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: none

    - name: Checkout Mezzio Sample
      uses: actions/checkout@v2
      with:
        repository: Naktibalda/codeception-mezzio-tests
        path: framework-tests
        ref: '5.0'
        submodules: recursive

    - name: Install Mezzio Sample
      run: composer update --no-dev --prefer-dist --no-interaction
      working-directory: framework-tests


    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer update --prefer-dist --no-progress --no-interaction --no-suggest

    - name: Run test suite
      run: php vendor/bin/codecept run functional -c framework-tests
