name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.4, 8.0, 8.1]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: none

    - name: Checkout Mezzio Sample
      uses: actions/checkout@v2
      with:
        repository: Slamdunk/codeception-mezzio-tests
        path: framework-tests
        submodules: recursive

    - name: Install Mezzio Sample on PHP 7
      if: matrix.php < 8
      run: composer update --no-dev --prefer-dist --no-interaction
      working-directory: framework-tests

    - name: Install Mezzio Sample on PHP 8
      if: matrix.php >= 8.0
      run: composer update --no-dev --prefer-dist --no-interaction --ignore-platform-req=php
      working-directory: framework-tests

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies on PHP 7
      if: matrix.php < 8
      run: composer install --prefer-dist --no-progress --no-interaction --no-suggest

    - name: Install dependencies on PHP 8
      if: matrix.php >= 8
      run: composer install --prefer-dist --no-progress --no-interaction --ignore-platform-req=php

    - name: Run test suite
      run: php vendor/bin/codecept run functional -c framework-tests
